### ISSUE TITLE
Warden Rake Setup issue

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/warden#92]
** Invoke setup (first_time)
** Execute setup
** Invoke setup:bin (first_time)
** Execute setup:bin
make clean all
cd wsh && make clean
...
cp src/wsh/wshd root/linux/skeleton/bin
cp src/wsh/wsh root/linux/skeleton/bin
cp src/iomux/iomux-spawn root/linux/skeleton/bin
cp src/iomux/iomux-link root/linux/skeleton/bin
cp src/iomux/iomux-spawn root/insecure/skeleton/bin
cp src/iomux/iomux-link root/insecure/skeleton/bin
** Invoke setup:rootfs (first_time)
** Execute setup:rootfs
mkdir -p /tmp/warden
sudo -E unshare -m root/linux/rootfs/setup.sh /tmp/warden/rootfs
unshare: failed to execute root/linux/rootfs/setup.sh: No permission
rake aborted!
Command failed with status (1): [sudo -E unshare -m root/linux/rootfs/setup...]
/usr/local/lib/ruby/1.9.1/rake/file_utils.rb:53:in `block in create_shell_runner'
/usr/local/lib/ruby/1.9.1/rake/file_utils.rb:45:in `call'
/usr/local/lib/ruby/1.9.1/rake/file_utils.rb:45:in `sh'
/usr/local/lib/ruby/1.9.1/rake/file_utils_ext.rb:39:in `sh'
/root/warden/warden/Rakefile:52:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/root/warden/warden/Rakefile:15:in `block in <top (required)>'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/usr/local/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/usr/local/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/usr/local/bin/rake:32:in `<main>'
Tasks: TOP => setup:rootfs

I have been getting this error with rake setup. I have setup all the necessary and this just pops up. It worked previously, no idea why is it not working now.

Please advise how to fix this?

**Comment by kennetham** [comment]
Solved. Warden folder setup.sh was not executable, to fix chmod 755 or chmod +x setup.sh
